#############################################################################!
# HELPER FUNCTIONS                                                       ####
#############################################################################!

#' Measurement models available in `bmm`
#'
#' @return A character vector of measurement models available in `bmm`
#' @export
#'
#' @examples
#' supported_models()
supported_models <- function() {
  supported_models <- lsp("bmm", pattern = "^\\.model_")
  supported_models <- sub("^\\.model_", "", supported_models)
  return(supported_models)
}

#' @title Generate a markdown list of the measurement models available in `bmm`
#' @description Used internally to automatically populate information in the README file
#' @return Markdown code for printing the list of measurement models available in `bmm`
#' @export
#' @keywords internal
print_pretty_models_md <- function() {
  ok_models <- supported_models()
  domains <- c()
  models <- c()
  for (model in ok_models) {
    m <- get_model(model)()
    domains <- c(domains, attr(m, 'domain'))
    models <- c(models, attr(m, 'name'))
  }
  unique_domains <- unique(domains)
  for (dom in unique_domains) {
    cat('####', dom, '\n\n')
    dom_models <- unique(models[domains == dom])
    for (model in dom_models) {
      cat('*', model, '\n\n')
    }
  }
}

#' Checks if the model is supported, and returns the model function
#' @param model A string with the name of the model supplied by the user
#' @param model_type Deprecated argument, use `model` instead
#' @return A list generated by a model function of type .model_*
#' @noRd
check_model <- function(model, model_type) {
  if (length(model_type) > 0) {
    warning("Argument 'model_type' is deprecated. Please use argument ",
            "'model' instead.")
    model <- model_type
  }

  ok_models <- supported_models()
  if (!model %in% ok_models) {
    stop(model, " is not a supported model. Supported ",
         "models are:\n", collapse_comma(ok_models))
  }

  return(get_model(model)())
}


#' retrieves one of the model functions below
#' @param model A string with the name of the model supplied by the user
#' @return A function of type .model_*
#' @details the returned object is a function. To get the model object, call the
#'   returned function, e.g. `get_model("2p")()`
#' @noRd
get_model <- function(model) {
  get(paste0('.model_', model), mode='function')
}

#############################################################################!
# MODELS                                                                 ####
#############################################################################!
# Each model should have a corresponding .model_* function which returns a list
# with the following attributes:
#   domain: the domain of the model (e.g. "Visual working memory")
#   name: the name of the model (e.g. "Two-parameter mixture model by Zhang and Luck (2008).")
#   citation: the citation for the model (e.g. "Zhang, W., & Luck, S. J. (2008).
#             Discrete fixed-resolution representations in visual working memory.
#             Nature, 453(7192), 233–235. https://doi.org/10.1038/nature06860")
#   class: a character vector with the class of the model (e.g. c("vwm","2p"))
#
# The class attribute is used by generic S3 functions to perform data checks and
# model configuration. The classes should be ordered from most general to most
# specific c("vwm","nontargets","3p"). A general class exists when the same operations
# can be performed on multiple models. For example, the '3p', 'IMMabc', 'IMMbsc'
# and 'IMMfull' models all have non-targets and setsize arguments, so the same
# data checks can be performed on all of them. The '2p' model does not have
# non-targets or setsize arguments, so it has a different class.

# TODO: add citation attribute to each model
# TODO: add a helper function to construct new models
# TODO: add model_info() function


.model_2p <- function() {
  out <- list()
  attr(out, "domain") <- "Visual working memory"
  attr(out, "name") <- "Two-parameter mixture model by Zhang and Luck (2008)."
  class(out) <- c("vwm","2p")
  out
}

.model_3p <- function() {
  out <- list()
  attr(out, "domain") <- "Visual working memory"
  attr(out, "name") <- "Three-parameter mixture model by Bays et al (2009)."
  class(out) <- c("vwm","nontargets","3p")
  out
}

.model_IMMabc <- function() {
  out <- list()
  attr(out, "domain") <- "Visual working memory"
  attr(out, "name") <- "Interference measurement model by Oberauer and Lin (2017)."
  class(out) <- c("vwm","nontargets","IMMabc")
  out
}

.model_IMMbsc <- function() {
  out <- list()
  attr(out, "domain") <- "Visual working memory"
  attr(out, "name") <- "Interference measurement model by Oberauer and Lin (2017)."
  class(out) <- c("vwm","nontargets", "IMMspatial","IMMbsc")
  out
}

.model_IMMfull <- function() {
  out <- list()
  attr(out, "domain") <- "Visual working memory"
  attr(out, "name") <- "Interference measurement model by Oberauer and Lin (2017)."
  class(out) <- c("vwm","nontargets","IMMspatial","IMMfull")
  out
}

