#############################################################################!
# HELPER FUNCTIONS                                                       ####
#############################################################################!

#' Measurement models available in `bmm`
#'
#' @return A character vector of measurement models available in `bmm`
#' @export
#'
#' @examples
#' supported_models()
supported_models <- function() {
  supported_models <- lsp("bmm", pattern = "^\\.model_")
  supported_models <- sub("^\\.model_", "", supported_models)
  return(supported_models)
}

#' @title Generate a markdown list of the measurement models available in `bmm`
#' @description Used internally to automatically populate information in the README file
#' @return Markdown code for printing the list of measurement models available in `bmm`
#' @export
#' @keywords internal
print_pretty_models_md <- function() {
  ok_models <- supported_models()
  domains <- c()
  models <- c()
  for (model in ok_models) {
    m <- get_model(model)()
    domains <- c(domains, attr(m, 'domain'))
    models <- c(models, attr(m, 'name'))
  }
  unique_domains <- unique(domains)
  for (dom in unique_domains) {
    cat('####', dom, '\n\n')
    dom_models <- unique(models[domains == dom])
    for (model in dom_models) {
      cat('*', model, '\n\n')
    }
  }
}

#' Checks if the model is supported, and returns the model function
#' @param model A string with the name of the model supplied by the user
#' @param model_type Deprecated argument, use `model` instead
#' @return A list generated by a model function of type .model_*
#' @noRd
check_model <- function(model, model_type) {
  if (length(model_type) > 0) {
    warning("Argument 'model_type' is deprecated. Please use argument ",
            "'model' instead.")
    model <- model_type
  }

  ok_models <- supported_models()
  if (!model %in% ok_models) {
    stop(model, " is not a supported model. Supported ",
         "models are:\n", collapse_comma(ok_models))
  }

  return(get_model(model)())
}


#' retrieves one of the model functions below
#' @param model A string with the name of the model supplied by the user
#' @return A function of type .model_*
#' @details the returned object is a function. To get the model object, call the
#'   returned function, e.g. `get_model("2p")()`
#' @noRd
get_model <- function(model) {
  get(paste0('.model_', model), mode='function')
}
